[versions]
vaadin = "24.3.4"
# https://repo1.maven.org/maven2/org/slf4j/slf4j-api/
slf4j = "2.0.11"
vok = "0.17"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
vaadin-boot = "com.github.mvysny.vaadin-boot:vaadin-boot:12.2"
vaadin-core = { module = "com.vaadin:vaadin-core", version.ref = "vaadin" }
junit-platform-launcher = "org.junit.platform:junit-platform-launcher:1.9.3"
karibu-testing = "com.github.mvysny.kaributesting:karibu-testing-v24:2.1.2"
flyway = "org.flywaydb:flyway-core:9.22.3"
h2 = "com.h2database:h2:2.2.224"
hikaricp = "com.zaxxer:HikariCP:5.0.1"
dynatest = "com.github.mvysny.dynatest:dynatest:0.24"
vok-db = { module = "eu.vaadinonkotlin:vok-framework-vokdb", version.ref = "vok" }
vaadin-security-simple = "com.github.mvysny.vaadin-simple-security:vaadin-simple-security:1.0"

[plugins]
vaadin = { id = "com.vaadin", version.ref = "vaadin" }
